"""Synchronous member-C repository with B-owned identifier semantics.

The caller owns transaction commit/rollback.  State changes use one conditional
SQL UPDATE so a completed record cannot later be reversed by a retry or race.
"""

from collections.abc import Iterable
from datetime import UTC, datetime

from sqlalchemy import select, update
from sqlalchemy.orm import Session

from backend.db.models import (
    GenerationRecord,
    TASK_STATUS_FAILED,
    TASK_STATUS_PENDING,
    TASK_STATUS_SUCCESS,
)
from backend.schemas import BusinessException, ErrorCode
from backend.validation import validate_copy


PERSISTED_FAILURE_CODES = frozenset(
    {
        "INTERNAL_ERROR",
        "MODEL_FAILED",
        "MODEL_OUTPUT_INVALID",
        "MODEL_TIMEOUT",
    }
)


def create_pending(
    session: Session,
    *,
    generation_id: str,
    created_at: datetime,
) -> GenerationRecord:
    """Create pending with the identifier already generated by B."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_created_at = _normalize_utc_datetime(
        created_at,
        error_message="任务创建时间无效",
    )

    record = GenerationRecord(
        task_id=normalized_id,
        status=TASK_STATUS_PENDING,
        created_at=normalized_created_at,
        updated_at=normalized_created_at,
    )
    session.add(record)
    session.flush()
    return record


def mark_success(
    session: Session,
    *,
    generation_id: str,
    image_summary: str,
    title: str,
    body: str,
    tags: Iterable[str],
    completed_at: datetime,
) -> GenerationRecord:
    """Validate C's rules, then atomically change pending to success."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_completed_at = _normalize_utc_datetime(
        completed_at,
        error_message="任务完成时间无效",
    )
    summary, normalized_title, normalized_body, normalized_tags = validate_copy(
        image_summary=image_summary,
        title=title,
        body=body,
        tags=tags,
    )

    result = session.execute(
        update(GenerationRecord)
        .where(
            GenerationRecord.task_id == normalized_id,
            GenerationRecord.status == TASK_STATUS_PENDING,
        )
        .values(
            status=TASK_STATUS_SUCCESS,
            image_description=summary,
            title=normalized_title,
            content=normalized_body,
            tags=normalized_tags,
            error_code=None,
            error_message=None,
            updated_at=normalized_completed_at,
        )
        .execution_options(synchronize_session=False)
    )
    if result.rowcount != 1:
        _raise_transition_error(session, normalized_id)
    return _get_record_or_raise(session, normalized_id)


def mark_failed(
    session: Session,
    *,
    generation_id: str,
    error_code: str,
    failed_at: datetime,
) -> GenerationRecord:
    """Atomically mark pending failed using only a stable error code."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_failed_at = _normalize_utc_datetime(
        failed_at,
        error_message="任务失败时间无效",
    )
    if error_code not in PERSISTED_FAILURE_CODES:
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "失败错误码无效",
        )

    result = session.execute(
        update(GenerationRecord)
        .where(
            GenerationRecord.task_id == normalized_id,
            GenerationRecord.status == TASK_STATUS_PENDING,
        )
        .values(
            status=TASK_STATUS_FAILED,
            error_code=error_code,
            error_message=None,
            updated_at=normalized_failed_at,
        )
        .execution_options(synchronize_session=False)
    )
    if result.rowcount != 1:
        _raise_transition_error(session, normalized_id)
    return _get_record_or_raise(session, normalized_id)


def get_record(session: Session, *, generation_id: str) -> GenerationRecord | None:
    """Look up one record without changing it."""
    normalized_id = _validate_generation_id(generation_id)
    return session.execute(
        select(GenerationRecord).where(GenerationRecord.task_id == normalized_id)
    ).scalar_one_or_none()


def _validate_generation_id(generation_id: str) -> str:
    if (
        not isinstance(generation_id, str)
        or not generation_id
        or len(generation_id) > 64
        or generation_id != generation_id.strip()
    ):
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "generation_id 无效",
        )
    return generation_id


def _normalize_utc_datetime(value: datetime, *, error_message: str) -> datetime:
    """Require an aware timestamp and store it as naive UTC for MySQL DATETIME."""
    if (
        not isinstance(value, datetime)
        or value.tzinfo is None
        or value.utcoffset() is None
    ):
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            error_message,
        )
    return value.astimezone(UTC).replace(tzinfo=None)


def _get_record_or_raise(session: Session, generation_id: str) -> GenerationRecord:
    record = session.execute(
        select(GenerationRecord)
        .where(GenerationRecord.task_id == generation_id)
        .execution_options(populate_existing=True)
    ).scalar_one_or_none()
    if record is None:
        raise BusinessException(ErrorCode.TASK_NOT_FOUND, "任务不存在")
    return record


def _raise_transition_error(session: Session, generation_id: str) -> None:
    status = session.execute(
        select(GenerationRecord.status).where(
            GenerationRecord.task_id == generation_id
        )
    ).scalar_one_or_none()
    if status is None:
        raise BusinessException(ErrorCode.TASK_NOT_FOUND, "任务不存在")
    raise BusinessException(
        ErrorCode.INVALID_STATE_TRANSITION,
        "任务已结束，不能再次修改状态",
    )
