"""Synchronous member-C repository with B-owned identifier semantics.

The caller owns transaction commit/rollback.  State changes use one conditional
SQL UPDATE so a completed record cannot later be reversed by a retry or race.
"""

from collections.abc import Iterable
from datetime import UTC, datetime

from sqlalchemy import select, update
from sqlalchemy.orm import Session

from backend.db.models import (
    GenerationRecord,
    MAX_IMAGE_PREVIEW_BYTES,
    TASK_STATUS_FAILED,
    TASK_STATUS_PENDING,
    TASK_STATUS_SUCCESS,
)
from backend.schemas import (
    BusinessException,
    ErrorCode,
    RiskAssessmentSnapshot,
)
from backend.validation import validate_copy


PERSISTED_FAILURE_CODES = frozenset(
    {
        "INTERNAL_ERROR",
        "MODEL_FAILED",
        "MODEL_OUTPUT_INVALID",
        "MODEL_TIMEOUT",
    }
)
IMAGE_PREVIEW_MEDIA_TYPES = frozenset({"image/jpeg", "image/webp"})


def create_pending(
    session: Session,
    *,
    generation_id: str,
    user_id: int | None,
    created_at: datetime,
) -> GenerationRecord:
    """Create pending with the identifier already generated by B."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_user_id = _validate_user_id(user_id)
    normalized_created_at = _normalize_utc_datetime(
        created_at,
        error_message="任务创建时间无效",
    )

    record = GenerationRecord(
        task_id=normalized_id,
        user_id=normalized_user_id,
        status=TASK_STATUS_PENDING,
        created_at=normalized_created_at,
        updated_at=normalized_created_at,
    )
    session.add(record)
    session.flush()
    return record


def mark_success(
    session: Session,
    *,
    generation_id: str,
    user_id: int | None,
    image_summary: str,
    title: str,
    body: str,
    tags: Iterable[str],
    risk_assessment: RiskAssessmentSnapshot,
    completed_at: datetime,
    image_preview: bytes | None = None,
    image_preview_media_type: str | None = None,
) -> GenerationRecord:
    """Validate C's rules, then atomically change pending to success."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_user_id = _validate_user_id(user_id)
    normalized_completed_at = _normalize_utc_datetime(
        completed_at,
        error_message="任务完成时间无效",
    )
    summary, normalized_title, normalized_body, normalized_tags = validate_copy(
        image_summary=image_summary,
        title=title,
        body=body,
        tags=tags,
    )
    normalized_preview, normalized_preview_media_type = _validate_image_preview(
        image_preview,
        image_preview_media_type,
    )
    normalized_risk_assessment = _normalize_risk_assessment(risk_assessment)

    result = session.execute(
        update(GenerationRecord)
        .where(
            GenerationRecord.task_id == normalized_id,
            _owner_predicate(normalized_user_id),
            GenerationRecord.status == TASK_STATUS_PENDING,
            GenerationRecord.deleted_at.is_(None),
        )
        .values(
            status=TASK_STATUS_SUCCESS,
            image_description=summary,
            title=normalized_title,
            content=normalized_body,
            tags=normalized_tags,
            risk_assessment=normalized_risk_assessment,
            image_path=None,
            image_preview=normalized_preview,
            image_preview_media_type=normalized_preview_media_type,
            error_code=None,
            error_message=None,
            updated_at=normalized_completed_at,
        )
        .execution_options(synchronize_session=False)
    )
    if result.rowcount != 1:
        _raise_transition_error(session, normalized_id, normalized_user_id)
    return _get_record_or_raise(session, normalized_id, normalized_user_id)


def mark_failed(
    session: Session,
    *,
    generation_id: str,
    user_id: int | None,
    error_code: str,
    failed_at: datetime,
) -> GenerationRecord:
    """Atomically mark pending failed using only a stable error code."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_user_id = _validate_user_id(user_id)
    normalized_failed_at = _normalize_utc_datetime(
        failed_at,
        error_message="任务失败时间无效",
    )
    if error_code not in PERSISTED_FAILURE_CODES:
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "失败错误码无效",
        )

    result = session.execute(
        update(GenerationRecord)
        .where(
            GenerationRecord.task_id == normalized_id,
            _owner_predicate(normalized_user_id),
            GenerationRecord.status == TASK_STATUS_PENDING,
            GenerationRecord.deleted_at.is_(None),
        )
        .values(
            status=TASK_STATUS_FAILED,
            error_code=error_code,
            error_message=None,
            updated_at=normalized_failed_at,
        )
        .execution_options(synchronize_session=False)
    )
    if result.rowcount != 1:
        _raise_transition_error(session, normalized_id, normalized_user_id)
    return _get_record_or_raise(session, normalized_id, normalized_user_id)


def get_record(
    session: Session,
    *,
    generation_id: str,
    user_id: int | None,
) -> GenerationRecord | None:
    """Look up one record only within its owning user's history."""
    normalized_id = _validate_generation_id(generation_id)
    normalized_user_id = _validate_user_id(user_id)
    return session.execute(
        select(GenerationRecord).where(
            GenerationRecord.task_id == normalized_id,
            _owner_predicate(normalized_user_id),
            GenerationRecord.deleted_at.is_(None),
        )
    ).scalar_one_or_none()


def delete_successful(
    session: Session,
    *,
    generation_id: str,
    user_id: int | None,
    deleted_at: datetime,
) -> bool | None:
    """Soft-delete one owned success without requiring SQL DELETE privilege.

    ``True`` means this call performed the update, ``False`` means that same
    owned success was already deleted, and ``None`` hides missing, wrong-owner,
    pending, and failed records behind one result.
    """
    normalized_id = _validate_generation_id(generation_id)
    normalized_user_id = _validate_user_id(user_id)
    normalized_deleted_at = _normalize_utc_datetime(
        deleted_at,
        error_message="任务删除时间无效",
    )
    state = session.execute(
        select(
            GenerationRecord.status,
            GenerationRecord.created_at,
            GenerationRecord.deleted_at,
        ).where(
            GenerationRecord.task_id == normalized_id,
            _owner_predicate(normalized_user_id),
        )
    ).one_or_none()
    if state is None or state.status != TASK_STATUS_SUCCESS:
        return None
    if state.deleted_at is not None:
        return False
    if normalized_deleted_at < state.created_at:
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "任务删除时间无效",
        )

    result = session.execute(
        update(GenerationRecord)
        .where(
            GenerationRecord.task_id == normalized_id,
            _owner_predicate(normalized_user_id),
            GenerationRecord.status == TASK_STATUS_SUCCESS,
            GenerationRecord.deleted_at.is_(None),
        )
        .values(
            image_path=None,
            image_preview=None,
            image_preview_media_type=None,
            image_description=None,
            user_input=None,
            title=None,
            content=None,
            tags=None,
            risk_assessment=None,
            error_code=None,
            error_message=None,
            deleted_at=normalized_deleted_at,
            updated_at=normalized_deleted_at,
        )
        .execution_options(synchronize_session=False)
    )
    if result.rowcount == 1:
        return True
    # A concurrent owner-scoped delete can win after the state read.  The
    # conditional UPDATE then changes zero rows, which is the idempotent case.
    return False


def _validate_generation_id(generation_id: str) -> str:
    if (
        not isinstance(generation_id, str)
        or not generation_id
        or len(generation_id) > 64
        or generation_id != generation_id.strip()
    ):
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "generation_id 无效",
        )
    return generation_id


def _validate_user_id(user_id: int | None) -> int | None:
    if user_id is None:
        return None
    if isinstance(user_id, bool) or not isinstance(user_id, int) or user_id <= 0:
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "user_id 无效",
        )
    return user_id


def _validate_image_preview(
    content: bytes | None,
    media_type: str | None,
) -> tuple[bytes | None, str | None]:
    if content is None and media_type is None:
        return None, None
    if (
        not isinstance(content, bytes)
        or not 1 <= len(content) <= MAX_IMAGE_PREVIEW_BYTES
        or media_type not in IMAGE_PREVIEW_MEDIA_TYPES
        or not _matches_preview_signature(content, media_type)
    ):
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "历史预览图无效",
        )
    return content, media_type


def _normalize_risk_assessment(
    value: RiskAssessmentSnapshot,
) -> dict[str, object]:
    try:
        snapshot = RiskAssessmentSnapshot.model_validate(value)
    except Exception:
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            "发布风险快照无效",
        ) from None
    return snapshot.model_dump(mode="json")


def _matches_preview_signature(content: bytes, media_type: object) -> bool:
    if media_type == "image/jpeg":
        return (
            len(content) >= 4
            and content.startswith(b"\xff\xd8\xff")
            and content.endswith(b"\xff\xd9")
        )
    if media_type == "image/webp":
        return (
            len(content) >= 12
            and content.startswith(b"RIFF")
            and content[8:12] == b"WEBP"
        )
    return False


def _normalize_utc_datetime(value: datetime, *, error_message: str) -> datetime:
    """Require an aware timestamp and store it as naive UTC for MySQL DATETIME."""
    if (
        not isinstance(value, datetime)
        or value.tzinfo is None
        or value.utcoffset() is None
    ):
        raise BusinessException(
            ErrorCode.VALIDATION_ERROR,
            error_message,
        )
    return value.astimezone(UTC).replace(tzinfo=None)


def _get_record_or_raise(
    session: Session,
    generation_id: str,
    user_id: int | None,
) -> GenerationRecord:
    record = session.execute(
        select(GenerationRecord)
        .where(
            GenerationRecord.task_id == generation_id,
            _owner_predicate(user_id),
            GenerationRecord.deleted_at.is_(None),
        )
        .execution_options(populate_existing=True)
    ).scalar_one_or_none()
    if record is None:
        raise BusinessException(ErrorCode.TASK_NOT_FOUND, "任务不存在")
    return record


def _raise_transition_error(
    session: Session,
    generation_id: str,
    user_id: int | None,
) -> None:
    status = session.execute(
        select(GenerationRecord.status).where(
            GenerationRecord.task_id == generation_id,
            _owner_predicate(user_id),
            GenerationRecord.deleted_at.is_(None),
        )
    ).scalar_one_or_none()
    if status is None:
        raise BusinessException(ErrorCode.TASK_NOT_FOUND, "任务不存在")
    raise BusinessException(
        ErrorCode.INVALID_STATE_TRANSITION,
        "任务已结束，不能再次修改状态",
    )


def _owner_predicate(user_id: int | None):
    """Compile legacy ownership as IS NULL, never as an omitted condition."""
    if user_id is None:
        return GenerationRecord.user_id.is_(None)
    return GenerationRecord.user_id == user_id
